[2020-10-23 15:22:08,800][Thread-4:139637741827840][task_id:django.request][log.py:228][ERROR][Internal Server Error: /]
Traceback (most recent call last):
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/engine.py", line 130, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/xms/PycharmProjects/Mypro/web/views.py", line 137, in index
    return render(request, 'pc/company.html')
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
[2020-10-23 15:22:08,815][Thread-3:139638454028032][task_id:django.request][log.py:228][ERROR][Internal Server Error: /]
Traceback (most recent call last):
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/engine.py", line 130, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/xms/PycharmProjects/Mypro/web/views.py", line 137, in index
    return render(request, 'pc/company.html')
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
[2020-10-23 15:22:08,821][Thread-5:139637733435136][task_id:django.request][log.py:228][ERROR][Internal Server Error: /]
Traceback (most recent call last):
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/engine.py", line 130, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/xms/PycharmProjects/Mypro/web/views.py", line 137, in index
    return render(request, 'pc/company.html')
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
[2020-10-23 15:22:08,823][Thread-4:139637741827840][task_id:django.server][basehttp.py:154][ERROR]["GET / HTTP/1.1" 500 137283]
[2020-10-23 15:22:08,824][Thread-3:139638454028032][task_id:django.server][basehttp.py:154][ERROR]["GET / HTTP/1.1" 500 137283]
[2020-10-23 15:22:08,825][Thread-5:139637733435136][task_id:django.server][basehttp.py:154][ERROR]["GET / HTTP/1.1" 500 137283]
[2020-10-29 12:26:42,450][Thread-2:139827109852928][task_id:django.request][log.py:228][ERROR][Internal Server Error: /profile/]
Traceback (most recent call last):
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/xms/PycharmProjects/Mypro/web/views.py", line 141, in about_company
    return render(request, 'pc/company')
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: pc/company
[2020-10-29 12:26:42,451][Thread-2:139827109852928][task_id:django.server][basehttp.py:154][ERROR]["GET /profile/ HTTP/1.1" 500 90628]
[2020-11-02 15:25:05,169][Thread-42:140177646663424][task_id:django.server][basehttp.py:154][ERROR]["GET /static/img/clture4.jpg HTTP/1.1" 500 59]
[2020-11-02 16:36:54,197][Thread-186:139722861045504][task_id:django.server][basehttp.py:154][ERROR]["GET /static/img/clutrue_1.png HTTP/1.1" 500 59]
[2020-11-02 17:17:39,406][Thread-288:139722223494912][task_id:django.server][basehttp.py:154][ERROR]["GET /static/img/clture4.jpg HTTP/1.1" 500 59]
[2020-11-03 17:07:52,599][Thread-41:140642638350080][task_id:django.server][basehttp.py:154][ERROR]["GET /static/my.jpg HTTP/1.1" 500 59]
[2020-11-03 17:07:53,202][Thread-39:140643698366208][task_id:django.server][basehttp.py:154][ERROR]["GET /static/js/jquery-1.12.3.min.js HTTP/1.1" 500 59]
[2020-11-05 16:57:44,067][Thread-82:139654334502656][task_id:django.server][basehttp.py:154][ERROR]["GET /static/scenes/kqdd.png HTTP/1.1" 500 59]
[2020-11-05 16:57:44,068][Thread-87:139654317717248][task_id:django.server][basehttp.py:154][ERROR]["GET /static/scenes/md.jpg HTTP/1.1" 500 59]
[2020-11-05 16:57:44,068][Thread-67:139654351288064][task_id:django.server][basehttp.py:154][ERROR]["GET /static/scenes/xzzz.png HTTP/1.1" 500 59]
[2020-11-05 17:52:27,272][Thread-111:139689868416768][task_id:django.server][basehttp.py:154][ERROR]["GET /static/scenes/kqdd.png HTTP/1.1" 500 59]
[2020-11-05 17:52:27,275][Thread-115:139690190964480][task_id:django.server][basehttp.py:154][ERROR]["GET /static/scenes/mhj.png HTTP/1.1" 500 59]
[2020-11-05 17:52:27,277][Thread-114:139689516332800][task_id:django.server][basehttp.py:154][ERROR]["GET /static/scenes/xzzz.png HTTP/1.1" 500 59]
[2020-11-11 14:50:58,820][Thread-3:140190328837888][task_id:django.server][basehttp.py:154][ERROR]["GET /static/img/first.png HTTP/1.1" 500 59]
[2020-11-11 14:51:19,290][Thread-2:140190651643648][task_id:django.server][basehttp.py:154][ERROR]["GET /static/img/second.png HTTP/1.1" 500 59]
[2020-11-11 14:51:43,877][Thread-5:140190312052480][task_id:django.server][basehttp.py:154][ERROR]["GET /static/img/third.png HTTP/1.1" 500 59]
[2020-11-11 16:19:23,908][Thread-60:139834916062976][task_id:django.server][basehttp.py:154][ERROR]["GET /static/scenes/myzz.png HTTP/1.1" 500 59]
[2020-11-17 14:23:33,080][uWSGIWorker1Core7:139804253644544][task_id:django.security.TooManyFieldsSent][exception.py:77][ERROR][The number of GET/POST parameters exceeded settings.DATA_UPLOAD_MAX_NUMBER_FIELDS.]
[2020-11-17 15:43:17,502][Thread-6:140431446755072][task_id:django.request][log.py:228][ERROR][Internal Server Error: /MGG/user/userip/]
Traceback (most recent call last):
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/options.py", line 564, in get_field
    return self.fields_map[field_name]
KeyError: 'user_show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 278, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 309, in _get_non_gfk_field
    field = opts.get_field(name)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/options.py", line 566, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Userip has no field named 'user_show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/base.py", line 33, in render
    return super().render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 341, in result_list
    'results': list(results(cl))}
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 318, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 309, in __init__
    super().__init__(*items)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 228, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 287, in lookup_field
    value = attr(obj)
  File "/home/xms/PycharmProjects/Mypro/user/admin.py", line 52, in user_show
    return MyUser.objects.filter(id=obj.name)[0].nick_name
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 965, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'AnonymousUser'
[2020-11-17 15:43:17,505][Thread-6:140431446755072][task_id:django.server][basehttp.py:154][ERROR]["GET /MGG/user/userip/ HTTP/1.1" 500 476083]
[2020-11-17 15:45:39,257][Thread-3:140701283264256][task_id:django.request][log.py:228][ERROR][Internal Server Error: /MGG/user/userip/]
Traceback (most recent call last):
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/options.py", line 564, in get_field
    return self.fields_map[field_name]
KeyError: 'user_show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 278, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 309, in _get_non_gfk_field
    field = opts.get_field(name)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/options.py", line 566, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Userip has no field named 'user_show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/base.py", line 33, in render
    return super().render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 341, in result_list
    'results': list(results(cl))}
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 318, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 309, in __init__
    super().__init__(*items)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 228, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 287, in lookup_field
    value = attr(obj)
  File "/home/xms/PycharmProjects/Mypro/user/admin.py", line 52, in user_show
    return MyUser.objects.filter(id=obj.name)[0].nick_name
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 965, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'AnonymousUser'
[2020-11-17 15:45:39,296][Thread-3:140701283264256][task_id:django.server][basehttp.py:154][ERROR]["GET /MGG/user/userip/ HTTP/1.1" 500 476344]
[2020-11-17 15:45:39,514][Thread-4:140701600036608][task_id:django.request][log.py:228][ERROR][Internal Server Error: /MGG/user/userip/]
Traceback (most recent call last):
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/options.py", line 564, in get_field
    return self.fields_map[field_name]
KeyError: 'user_show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 278, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 309, in _get_non_gfk_field
    field = opts.get_field(name)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/options.py", line 566, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Userip has no field named 'user_show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/base.py", line 33, in render
    return super().render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 341, in result_list
    'results': list(results(cl))}
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 318, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 309, in __init__
    super().__init__(*items)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 228, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 287, in lookup_field
    value = attr(obj)
  File "/home/xms/PycharmProjects/Mypro/user/admin.py", line 52, in user_show
    return MyUser.objects.filter(id=obj.name)[0].nick_name
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 965, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'AnonymousUser'
[2020-11-17 15:45:39,588][Thread-5:140701274760960][task_id:django.request][log.py:228][ERROR][Internal Server Error: /MGG/user/userip/]
Traceback (most recent call last):
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/options.py", line 564, in get_field
    return self.fields_map[field_name]
KeyError: 'user_show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 278, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 309, in _get_non_gfk_field
    field = opts.get_field(name)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/options.py", line 566, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Userip has no field named 'user_show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/base.py", line 33, in render
    return super().render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 341, in result_list
    'results': list(results(cl))}
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 318, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 309, in __init__
    super().__init__(*items)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 228, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 287, in lookup_field
    value = attr(obj)
  File "/home/xms/PycharmProjects/Mypro/user/admin.py", line 52, in user_show
    return MyUser.objects.filter(id=obj.name)[0].nick_name
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 965, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'AnonymousUser'
[2020-11-17 15:45:39,647][Thread-4:140701600036608][task_id:django.server][basehttp.py:154][ERROR]["GET /MGG/user/userip/ HTTP/1.1" 500 476344]
[2020-11-17 15:45:39,663][Thread-6:140701266106112][task_id:django.request][log.py:228][ERROR][Internal Server Error: /MGG/user/userip/]
Traceback (most recent call last):
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/options.py", line 564, in get_field
    return self.fields_map[field_name]
KeyError: 'user_show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 278, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 309, in _get_non_gfk_field
    field = opts.get_field(name)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/options.py", line 566, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Userip has no field named 'user_show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/base.py", line 33, in render
    return super().render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 341, in result_list
    'results': list(results(cl))}
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 318, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 309, in __init__
    super().__init__(*items)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 228, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 287, in lookup_field
    value = attr(obj)
  File "/home/xms/PycharmProjects/Mypro/user/admin.py", line 52, in user_show
    return MyUser.objects.filter(id=obj.name)[0].nick_name
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 965, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'AnonymousUser'
[2020-11-17 15:45:39,665][Thread-5:140701274760960][task_id:django.server][basehttp.py:154][ERROR]["GET /MGG/user/userip/ HTTP/1.1" 500 476344]
[2020-11-17 15:45:39,665][Thread-6:140701266106112][task_id:django.server][basehttp.py:154][ERROR]["GET /MGG/user/userip/ HTTP/1.1" 500 476344]
[2020-11-17 15:45:43,710][Thread-6:140701266106112][task_id:django.request][log.py:228][ERROR][Internal Server Error: /MGG/user/userip/]
Traceback (most recent call last):
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/options.py", line 564, in get_field
    return self.fields_map[field_name]
KeyError: 'user_show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 278, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 309, in _get_non_gfk_field
    field = opts.get_field(name)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/options.py", line 566, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Userip has no field named 'user_show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/base.py", line 33, in render
    return super().render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 341, in result_list
    'results': list(results(cl))}
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 318, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 309, in __init__
    super().__init__(*items)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 228, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 287, in lookup_field
    value = attr(obj)
  File "/home/xms/PycharmProjects/Mypro/user/admin.py", line 52, in user_show
    return MyUser.objects.filter(id=obj.name)[0].nick_name
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 965, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'AnonymousUser'
[2020-11-17 15:45:43,711][Thread-6:140701266106112][task_id:django.server][basehttp.py:154][ERROR]["GET /MGG/user/userip/ HTTP/1.1" 500 476218]
[2020-11-17 15:45:51,416][Thread-6:140701266106112][task_id:django.request][log.py:228][ERROR][Internal Server Error: /MGG/user/userip/]
Traceback (most recent call last):
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/options.py", line 564, in get_field
    return self.fields_map[field_name]
KeyError: 'user_show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 278, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 309, in _get_non_gfk_field
    field = opts.get_field(name)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/options.py", line 566, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Userip has no field named 'user_show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/base.py", line 33, in render
    return super().render(context)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 341, in result_list
    'results': list(results(cl))}
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 318, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 309, in __init__
    super().__init__(*items)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 228, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 287, in lookup_field
    value = attr(obj)
  File "/home/xms/PycharmProjects/Mypro/user/admin.py", line 52, in user_show
    return MyUser.objects.filter(id=obj.name)[0].nick_name
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/xms/.pyenv/versions/django/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 965, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'AnonymousUser'
[2020-11-17 15:45:51,416][Thread-6:140701266106112][task_id:django.server][basehttp.py:154][ERROR]["GET /MGG/user/userip/ HTTP/1.1" 500 476083]
